# Generated by Django 3.1 on 2020-08-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200821_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefilemodel',
            name='image',
            field=models.ImageField(upload_to='input/', verbose_name='img'),
        ),
    ]
