# Generated by Django 3.1 on 2020-08-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200822_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefilemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='input/'),
        ),
    ]
