# Generated by Django 3.1 on 2020-08-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200822_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefilemodel',
            name='name',
        ),
    ]
